const DB_NAME = "whitemint-library";
const DB_VERSION = 1;
const ARTICLES = "articles";
const META = "meta";
const LEGACY_KEY = "whitemint:articles";
const FALLBACK_KEY = "whitemint:articles-v2";
const canUseDb = () => typeof indexedDB !== "undefined";
const normalizeUrl = (url = "") => { try { const parsed = new URL(url); parsed.hash = ""; return parsed.toString(); } catch { return String(url).trim(); } };
const makeId = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const normalize = (article = {}) => ({ ...article, id: article.id || makeId(), normalizedUrl: normalizeUrl(article.url), collectionIds: Array.isArray(article.collectionIds) ? [...new Set(article.collectionIds)] : ["inbox"] });
const request = (value) => new Promise((resolve, reject) => { value.onsuccess = () => resolve(value.result); value.onerror = () => reject(value.error || new Error("Local database request failed.")); });
const completed = (transaction) => new Promise((resolve, reject) => { transaction.oncomplete = resolve; transaction.onerror = () => reject(transaction.error || new Error("Local database transaction failed.")); transaction.onabort = () => reject(transaction.error || new Error("Local database transaction aborted.")); });
let database;
function openDatabase() { if (!canUseDb()) return Promise.reject(new Error("IndexedDB is unavailable on this device.")); database ||= new Promise((resolve, reject) => { const opening = indexedDB.open(DB_NAME, DB_VERSION); opening.onupgradeneeded = () => { const db = opening.result; const articles = db.objectStoreNames.contains(ARTICLES) ? opening.transaction.objectStore(ARTICLES) : db.createObjectStore(ARTICLES, { keyPath: "id" }); if (!articles.indexNames.contains("normalizedUrl")) articles.createIndex("normalizedUrl", "normalizedUrl"); if (!articles.indexNames.contains("dateAdded")) articles.createIndex("dateAdded", "dateAdded"); if (!db.objectStoreNames.contains(META)) db.createObjectStore(META, { keyPath: "key" }); }; opening.onsuccess = () => resolve(opening.result); opening.onerror = () => reject(opening.error || new Error("IndexedDB could not be opened.")); }); return database; }
async function transaction(stores, mode, callback) { const db = await openDatabase(); const tx = db.transaction(stores, mode); const result = await callback(tx); await completed(tx); return result; }
function fallbackRead() { try { return JSON.parse(localStorage.getItem(FALLBACK_KEY) || localStorage.getItem(LEGACY_KEY) || "[]"); } catch { return []; } }
function fallbackWrite(value) { try { localStorage.setItem(FALLBACK_KEY, JSON.stringify(value)); } catch (error) { if (error?.name === "QuotaExceededError") throw new Error("Device storage is full. Remove an article or free space to continue."); throw error; } }
export async function migrateLegacyArticles(values = [], log = () => {}) { const legacy = Array.isArray(values) ? values.map(normalize) : []; if (!canUseDb()) { if (!localStorage.getItem(FALLBACK_KEY)) fallbackWrite(legacy); return; } const marker = await transaction([META], "readonly", (tx) => request(tx.objectStore(META).get("migrated"))); if (marker?.value) return; await transaction([ARTICLES], "readwrite", async (tx) => { const store = tx.objectStore(ARTICLES); if ((await request(store.getAll())).length === 0) legacy.forEach((item) => store.put(item)); }); await transaction([META], "readwrite", (tx) => { tx.objectStore(META).put({ key: "migrated", value: true }); return Promise.resolve(); }); if (legacy.length) log("storage.migrated", `${legacy.length} article${legacy.length === 1 ? "" : "s"} moved to the local library.`); }
export async function listArticles() { if (!canUseDb()) return fallbackRead().map(normalize); return (await transaction([ARTICLES], "readonly", (tx) => request(tx.objectStore(ARTICLES).getAll()))).map(normalize).sort((a, b) => new Date(b.dateAdded || 0) - new Date(a.dateAdded || 0)); }
export async function saveArticle(value) { const item = normalize(value); if (!canUseDb()) { const all = await listArticles(); const old = all.find((a) => a.normalizedUrl === item.normalizedUrl); if (old) item.id = old.id; fallbackWrite([item, ...all.filter((a) => a.id !== item.id)]); return item; } const old = await transaction([ARTICLES], "readonly", (tx) => request(tx.objectStore(ARTICLES).index("normalizedUrl").get(item.normalizedUrl))); if (old?.id) item.id = old.id; await transaction([ARTICLES], "readwrite", (tx) => { tx.objectStore(ARTICLES).put(item); return Promise.resolve(); }); return item; }
export async function removeArticle(id) { if (!canUseDb()) { const all = await listArticles(); const found = all.find((a) => a.id === id) || null; fallbackWrite(all.filter((a) => a.id !== id)); return found; } const found = await transaction([ARTICLES], "readonly", (tx) => request(tx.objectStore(ARTICLES).get(id))); await transaction([ARTICLES], "readwrite", (tx) => { tx.objectStore(ARTICLES).delete(id); return Promise.resolve(); }); return found || null; }
export const restoreArticle = saveArticle;
export async function setArticleCollections(id, collectionIds = []) { const all = await listArticles(); const article = all.find((item) => item.id === id); if (!article) throw new Error("Article not found."); article.collectionIds = [...new Set(collectionIds)]; if (!canUseDb()) { fallbackWrite(all.map((item) => item.id === article.id ? article : item)); } else { await transaction([ARTICLES], "readwrite", (tx) => { tx.objectStore(ARTICLES).put(article); return Promise.resolve(); }); } return article; }
